///////////////////////////////////////////////////////////
//  DFSGraph.cs
//  Implementation of the Class Graph
//  Generated by Enterprise Architect
//  Created on:      18-Dec-2017 11:28:00 PM
//  Original author: Nick
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Algorithms {
	public class Graph<T> {

		public Graph(){

		}
	

		/// 
		/// <param name="vertices"></param>
		/// <param name="edges"></param>
		public Graph(IEnumerable<T> vertices, IEnumerable<Tuple<T, T>> edges){

		}

		/// 
		/// <param name="edge"></param>
		private void AddEdge(Tuple<T, T> edge){

		}

		/// 
		/// <param name="vertex"></param>
		private void AddVertex(T vertex){

		}

		public Dictionary<T, HashSet<T>> AdjacencyList{
			get;
		} = new Dictionary<T, HashSet<T>>();


	}//end Graph

}//end namespace Algorithms