///////////////////////////////////////////////////////////
//  IAlgorithm.cs
//  Implementation of the Interface IAlgorithm
//  Generated by Enterprise Architect
//  Created on:      16-Dec-2017 10:35:19 PM
//  Original author: Nick
///////////////////////////////////////////////////////////

namespace CardGamesAPI
{
    public interface INode
    {
    }
}